# Site settings
my_name: Rachel Keranen
description: "Writer. Editor. Wanderer."
baseurl: ""
safe: true

# Build settings
markdown: kramdown
permalink: pretty

# Page defaults
defaults:
  -
    scope:
      path: "" # == all files
      type: "page"
    values:
      layout: "page"
      show_title: true
